###
//registration
POST http://localhost:4000/api/registration
Content-Type: application/json

{
    "username": "cusenremove",
    "password": "123456"
}

###
//login
POST https://sendeptraidb.herokuapp.com/api/login
Content-Type: application/json

{
    "username": "cusenbonchen",
    "password": "123456"
}
###
//delete user
DELETE http://localhost:4000/api/users/remove/60d0b301a14781486812d26d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

###
//xem toàn bộ product
GET http://localhost:4000/api/product 

###
//thêm product
POST http://localhost:4000/api/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

{
    "name":"Sen",
    "description":"Thông tin sản phẩm được ghi ở đây để cho nó dài ra người ta dễ đọc",
    "price":"150.000đ",
    "images":"abc.jpg"
}

###
//Sửa product
PUT http://localhost:4000/api/product/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

{
    "name":"Sen",
    "description":"Thông tin sản phẩm được ghi ở đây để cho nó dài ra người ta dễ đọc",
    "price":"150.000đ",
    "images":"abc.jpg"
}
###
//xóa product
DELETE http://localhost:4000/api/product/delete/123
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

###
//thêm list images
POST http://localhost:4000/api/listImage/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

{
    "files":["list file"] 
}

### 
// tìm list images dựa by id product
GET http://localhost:4000/api/images/123123


### 
// search products
POST http://localhost:4000/api/search-products
Content-Type: application/json

{
    "query": "sò"
}

###
//pagination products
POST http://localhost:4000/api/products
Content-Type: application/json

{ 
    "page": "2",
    "limit": "1"
}
###
//xem settings
GET http://localhost:4000/api/setting
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8


###
//thêm settings
POST http://localhost:4000/api/settings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

{
    "logo":"abc.svg",
    "companyname":"Tuân Company1",
    "slogan":"đây là câu slogan chất chơi con bà dơi",
    "facebook":"facebook.com",
    "zalo":"zalo.me",
    "skype":"abc@sksdjsd.skpe",
    "viber":"01230111",
    "instargram":"intersen",
    "mail":"abc@gmail.com",
    "address":"đây là địa chỉ",
    "phone":"0123123132",
    "map": "map"
}
###
//Update settings
PUT http://localhost:4000/api/updatesettings/60d97bd83d980e1878755a6a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

{
    "logo":"abc.svg",
    "companyname":"Tuân Company2",
    "slogan":"đây là câu slogan chất chơi con bà dơi3",
    "facebook":"facebook.com/cusenbonchen",
    "zalo":"zalo.me",
    "skype":"abc@sksdjsd.skpe",
    "viber":"01230111",
    "instargram":"intersen",
    "mail":"abc@gmail.com",
    "address":"đây là địa chỉ",
    "phone":"0123123132",
    "map":"map"
}

###
// xem toàn bộ blogs
GET http://localhost:4000/api/blog/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8
###
// thêm mới blog
POST http://localhost:4000/api/blog/add
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

{
   "title":"dầu gió 11", 
   "description": "viết vài dòng cho dài dài",
   "content": "lorem a cà chemlorem a cà chemlorem a cà chemlorem a cà chemlorem a cà chem..",
   "thumbnail":"1a123.jpg",
   "category":"Làm đẹp"
}
###
// Sửa blog
PUT http://localhost:4000/api/blog/edit/60f1517590eda8149c3ba0e9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

{
   "title":"bài post số 1", 
   "description": "viết vài dòng cho dài dài edit2",
   "content": "edit2 lorem a cà chemlorem a cà chemlorem a cà chemlorem a cà chemlorem a cà chem..",
   "thumbnail":"edit21a123.jpg"
}
###
//xóa blog
DELETE http://localhost:4000/api/blog/remove/60f15a98af740108fc044f69
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8

### 
// search blog
POST http://localhost:4000/api/search-blog
Content-Type: application/json

{
    "query": "dầu gió"
}
###
//pagination blogs
POST http://localhost:4000/api/blogs
Content-Type: application/json

{ 
    "page": "3",
    "limit": "5"
}

###
//details blog
GET http://localhost:4000/api/blog/detail/60f5310746497c2128e1c926
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGQwYjMwMWExNDc4MTQ4NjgxMmQyNmQiLCJpYXQiOjE2MjQ1NTA2MTN9.4-J1AXf-GZRab41S06vCBcgkvy4sK4_QupdUfKlEwj8
